# docker-compose.db.yml (v3) - correct init.sql path
name: reco-db
networks:
  reco_net:
    external: true

volumes:
  pgdata:
    name: reco_pgdata

services:
  postgres:
    image: postgres:16
    container_name: reco_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    networks:
      - reco_net
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
